### ISSUE TITLE
améliorer dynamisme affichage sur smartphone

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#100]
les images sont trop larges sur un smartphone --> règle à utiliser 

sur smartphone, utiliser 100% de la largeur disponible
sur PC, utiliser une taille fixe en pixel.

sur PC, la largeur de la colonne de droite n'est pas totalement utilisée. Par exemple la carte google n'utilise pas 100% de la largeur de la colonne.

Sur la page affichant les détail d'un commerce en particulier, le logo du commerce est aplati verticalement.

**Comment by samouraii** [comment]
@ Fabian, Peut tu montrer un exemple car je ne vois pas le problème

**Comment by samouraii** [comment]
@fdortu

**Comment by fdortu** [comment]
On y regarde ensemble lors du GT informatique, sans doute le 12 juin 2017...
