### ISSUE TITLE
Dans la Zone Admin Membre, indiquer si un membre est inscrit comme sympathisant ou effectif

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#105]
Ajouter une check box pour voir si le membre est sympathisant ou effectif

**Comment by Laurent5** [comment]
Il faut du coup lié un membre à une cotisation et une date d'expiration ...

Je m'en occupe !

Bizz Bizz

**Comment by fdortu** [comment]
Précision du texte à afficher à coté d'une combo box (maintenant c'est une check box)

Je souhaite me faire membre usager *sympathisant* de l'asbl Ropi.
Je souhaite me faire membre usager *effectif* de l'asbl Ropi - Cotisation de 15 € ou 10 R. 
    (le membre effectif possède le droit de vote à l'Assemblé Générale de l'asbl)

**Comment by fdortu** [comment]
Cela concerne aussi bien la partie admin que la partie utilisateur

**Comment by Laurent5** [comment]
Allez ... D'accord ;-)
