### ISSUE TITLE
gestion des cotisations - usager vs prestataires et assoces

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#115]
proposition de terminologie à utiliser : 

Zone Admin Membre  --devient--> Zone Admin Utilisateurs  
Zone Admin Commerces

(car un commerce est aussi un membre, et à contrario tous les utilisateurs ne sont pas des membres (juste sympathisant))

Dans la gestion des cotisations du listing des utilisateurs (http://dev.ropi.be/admin/user/listing), *ne pas* donner le choix du collège, car un utilisateur est d'office membre du collège usager (sauf si qualité de sympathisant).

Par contre dans le listing des commerçants (http://dev.ropi.be/my/admin/commerces), ajouter les mêmes données de cotisation que pour les utilisateurs, avec ici le choix du collège (collège prestataire ou collège association). Ici il faut forcer l'appartenance à un collège, car un commerce ne peut pas être sympathisant.

**Comment by Laurent5** [comment]
Ok.

La partie association des collèges sera traîté dans #121
