### ISSUE TITLE
Erreur de parsing quand un pattern n'est pas défini

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#119]
Erreur de parsing quand un pattern n'est pas défini

ici j'ai utilisé *[telSupport] qui n'est pas encore défini :

# Message d'erreur
 todo

info@ropi.be

support@ropi.be

info@ropi.be

 exception 'Symfony\Component\Translation\Exception\NotFoundResourceException' with message 'Ce paramètres telSupport n'a pas été trouvé' in /var/www/ropi.dev/siteWebV2/src/Ropi/ParametresBundle/Service/Parametres.php:34 Stack trace: #0 /var/www/ropi.dev/siteWebV2/src/Ropi/CMSBundle/Parser/Parser.php(88): Ropi\ParametresBundle\Service\Parametres->getValueOf('telSupport') #1 /var/www/ropi.dev/siteWebV2/src/Ropi/CMSBundle/Parser/Parser.php(58): Ropi\CMSBundle\Parser\Parser->parametresRetour('*[telSupport]') #2 /var/www/ropi.dev/siteWebV2/src/Ropi/CMSBundle/Parser/Parser.php(35): Ropi\CMSBundle\Parser\Parser->doIt('/[*][[][[:alnum...', 'parametresRetou...', '

 todoparse('

 todogetAttribute(Object(Ropi\CMSBundle\Parser\Parser), 'parse', Array, 'method') #6 /var/www/ropi.dev/siteWebV2/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_f9e93b42411fdfca6f4e83c2b784302da0412f32beadc84c8fbcf383859c0237->block_content(Array, Array) #7 /var/www/ropi.dev/siteWebV2/var/cache/prod/twig/8e/8e09a62a04ccd0dbbb4f7c245cfc19871431f9dbc5a496ba663c20db2189f061.php(160): Twig_Template->displayBlock('content', Array, Array) #8 /var/www/ropi.dev/siteWebV2/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_fed3d8cd5b6fd7239729a00b653da7783d22784ad250bbf94ec2a0a5654d1259->doDisplay(Array, Array) #9 /var/www/ropi.dev/siteWebV2/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #10 /var/www/ropi.dev/siteWebV2/var/cache/prod/twig/54/547027cebb32128bf855644e1ea7c3e221b89066f6b9bbf0019d0bbda72bb599.php(24): Twig_Template->display(Array, Array) #11 /var/www/ropi.dev/siteWebV2/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_f9e93b42411fdfca6f4e83c2b784302da0412f32beadc84c8fbcf383859c0237->doDisplay(Array, Array) #12 /var/www/ropi.dev/siteWebV2/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #13 /var/www/ropi.dev/siteWebV2/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array) #14 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php(50): Twig_Template->render(Array) #15 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(50): Symfony\Bridge\Twig\TwigEngine->render('RopiCMSBundle:D...', Array) #16 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(75): Symfony\Bundle\TwigBundle\TwigEngine->render('RopiCMSBundle:D...', Array) #17 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php(212): Symfony\Bundle\TwigBundle\TwigEngine->renderResponse('RopiCMSBundle:D...', Array, NULL) #18 /var/www/ropi.dev/siteWebV2/src/Ropi/CMSBundle/Controller/DefaultController.php(97): Symfony\Bundle\FrameworkBundle\Controller\Controller->render('RopiCMSBundle:D...', Array) #19 [internal function]: Ropi\CMSBundle\Controller\DefaultController->getPageAction('Contacts', 'Nous contacter') #20 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(148): call_user_func_array(Array, Array) #21 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #22 /var/www/ropi.dev/siteWebV2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(169): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /var/www/ropi.dev/siteWebV2/web/app.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #24 {main}

**Comment by Laurent5** [comment]
Pas cool ...
