### ISSUE TITLE
Problème d'escaping (backslash) des caractères spéciaux 

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#13]
Dans toutes les pages (sauf le texte de la map accueil), le caractère apostrophe (') est précédé d'un backslah (\), voir d'un double backslash (\\)

**Comment by Laurent5** [comment]
Je prend en charge

**Comment by Laurent5** [comment]
Le problème venait des fixtures qui étaient escapée au fur et à mesure sans jamais être déchapé
