### ISSUE TITLE
bug : un commerce est autotiquement associé à tous les utilisateurs inscrits

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#137]
Je viens de créer un commerce Fonds du Petit Marais avec mon compte utilisateur fdortu.
Dans la liste de utilisateurs associés au commerce, il me semble que tous les utilisateurs enregistrés sont indiqués alors qu'il ne devrait y avoir que moi (fdortu).

Voir snapshot ci-dessous 

![bug_association_commerce_a_utilisateur](https://cloud.githubusercontent.com/assets/7003203/18117206/67920052-6f4d-11e6-98fc-d44a9dbd070f.png)

**Comment by Laurent5** [comment]
Coucou,

En fait cela est logique car tu es en droit admin sur le site, normalement un utilisateur standard ne vois pas ce choix.

Je ferme (temporairement?) cette issue.

**Comment by fdortu** [comment]
Oui effectivement tu as raison pour la liste des personnes liées à un commerce puisque l'admin doit pouvoir la choisir. Mon franc tombe.

Cependant, je n'arrive toujours pas à créer un commerce. Il n'apparait pas dans la liste des commerces à valider ni dans la liste des commerçants sur la page publique. 
La je viens de réessayer et j'obtiens une erreur 500.
