### ISSUE TITLE
Carte à remanier

### ISSUE THREAD

**Issue by Laurent5** [RopiMons/siteWebV2#143]
Problème de onmouseover

**Comment by samouraii** [comment]
@fdortu Voila pour l'histoire de la carte j'ai trouvé le problème, cela concerne des balises qui ne se ferme pas à cause des 100 caractère de la news. Pour le moment on peut te proposer 2 solutions de correction, soit afficher quelque Titres de News, ou alors un champs resume qui s'affiche complement ?

Bien à toi

**Comment by samouraii** [comment]
Pour le moment on affiche qu'un titre

**Comment by samouraii** [comment]
@fdortu que le titre cela te va ?

**Comment by fdortu** [comment]
Oui c'est super comme ça!
