### ISSUE TITLE
problème de redirection de http://compta.ropi.be/

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#144]
L'adresse http://compta.ropi.be/ lie vers la page web d'un jeu.

Pour le moment, il n'y a pas de compta en ligne, serait-il donc possible de pointer vers un répertoire dans lequel on copierait les bilans comptables ?

**Comment by samouraii** [comment]
Oui, mais tu veux quoi? une page sur notre site ? il suffi que tu la crée cette page comme pour les autres, et on places les bilans

**Comment by fdortu** [comment]
Ok, on fait comme ça. Je me crée une issue dans Ropi doc
