### ISSUE TITLE
Problème design

### ISSUE THREAD

**Issue by samouraii** [RopiMons/siteWebV2#31]
La carte, et l'info bulle passe en dessous du foot bar sur smartphone

**Comment by fdortu** [comment]
Ben zut alors, je m'appretais à introduire cette issue là précisément. 
Tu me retires tout mon plaisir ;-P

**Comment by fdortu** [comment]
Et du coup le texte infobulle n'apparait plus du tout

**Comment by samouraii** [comment]
ahah je suis désolé :( je traite cela des que je rentre
