### ISSUE TITLE
Limitation adhésion prestataires à code postaux 70xx et 73xx

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#34]
Limiter le ropi aux codes 70xx et 73xx 

73 correspond à Quaregnon, Hornu, Boussu qui sont des petites villes peut susceptibles de créer leurs propres monnaies locales dans le court terme
Avec 70xx, on inclut aussi Braine-le-compte, ce qui n'est pas très heureux vu qu'il y a la Minuto, mais comme Ropi et Minuto (couvre toute la wallonie) sont de conception assez différente ce n'est pas très grave.

Au delà on va vers des plus grandes villes comme Binche et Charleroi (71) et Ath (79) qui ont des intentions de création de monnaie.

**Comment by Laurent5** [comment]
Fait dans c6593a8d34a1f2312183ee2e655d33b939813bf2
