### ISSUE TITLE
Petit CV à mettre sur le site

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#35]
Salut Joëlle, pourrais-tu m'envoyer un petit CV à mettre sur le site (http://dev.ropi.be/page/Ropi/L'%C3%A9quipe).

Tu  peux me l'écrire ici en réponse de l'issue, ainsu que la photo (drap and drop dans la zone)

**Comment by JoBierna** [comment]
je n'ai pas de photo por l'insaint, le texte : Je suis bachelière en infographie.Je suis bénévole dans différents associations et asbl montoises. Je suis co-fondatrice d'une brasserie locale où je gère la partie graphique.
