### ISSUE TITLE
email de confirmation de l'inscription est non fonctionnel

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#62]
Inscription sur le site du Ropi

Bonjour Tu viens de t'inscrire sur le site du Ropi
J'ai créé un compte (Henry Ford, login: hford)

Le mail de confirmatio m'est envoyé correctement mais le lien de confirmation ne fonctionne pas (erreur 500).
Voici le contenu du mail en question avec le lien.

Pour te connecter à ton compte tu dois commencer par valider ton inscription en cliquant sur le lien suivant:
Tes identifiants de connection

Pour rappel, voici tes identifiants de connection :
Ton login : hford

Pour te connecter à ton compte tu dois commencer par valider ton inscription en cliquant sur le lien suivant:

http://dev.ropi.be/confirmation/40/1db43612ffa0da907efbe1a21a0b1b96

A très bientôt sur www.ropi.be

L'équipe du Ropi

**Comment by samouraii** [comment]
Ok parfait je vérifie cela dans la soirée :)

**Comment by samouraii** [comment]
OK bug detecter, l'id de l'utilisateur n'est plus rajouter à la bdd.
