### ISSUE TITLE
ajouter la possibilité d'éditer ses données personnelles

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#63]
Après inscription d'un utilisateur, il faudrait donner la possibilité de rééditer ses données personnelles, comme l'adresse de livraison et le numéro de téléphone.

**Comment by Laurent5** [comment]
@samouraii tu sais me donner les routes vers ces fonctionnalités ? Tu l'implémente toi dans le menu d'admin ?

**Comment by samouraii** [comment]
Alors il y 2 route 
pour son compte c'est /my/account 
pour les admins /admin/user/listing ==> listing des utilisateurs

**Comment by Laurent5** [comment]
Si je m’occupe de l’implémentation, tu sais me donner le nom de la route (Name) ?

 

A tantôt :)

 

 

De : Huygens Adrien [mailto:notifications@github.com] 
Envoyé : vendredi 20 novembre 2015 15:37
À : RopiMons/siteWebV2 <siteWebV2@noreply.github.com>
Cc : Laurent Cardon <contact@laurentcardon.be>
Objet : Re: [siteWebV2] ajouter la possibilité d'éditer ses données personnelles (#63)

 

Alors il y 2 route 
pour son compte c'est /my/account 
pour les admins /admin/user/listing ==> listing des utilisateurs

**Comment by samouraii** [comment]
Je te les donne mais je sais pas comment tu fait pour les rajouter à la bdd mais j'ai surtout pas encore pris le temps de regarder. 

ropi_account => my account

Ropi_admin_user_listing

**Comment by samouraii** [comment]
Pour la partie admin c'est encore dans le code ?

**Comment by Laurent5** [comment]
Bingo ^^.  <https://github.com/notifications/beacon/AAmD72T1lzZQrNPE-gxkO8Fz_04ca21xks5pHy0pgaJpZM4Gg_mv.gif>

**Comment by Laurent5** [comment]
Je m'y attaque ...
