### ISSUE TITLE
liaison de l'inscription sur le web à l'adhésion en tant que membre effectif

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#64]
Comment choisir l'inscription en tant que membre effectif apès inscription (j'avais cru comprendre que Laurent avait déjà implémenté la possibilité mais je ne trouve pas comment faire).

Cette adhésion doit permettre le choix du collège.

**Comment by Laurent5** [comment]
Bingo

**Comment by Laurent5** [comment]
Qu'entends-tu par *Cette adhésion doit permettre le choix du collège.* ?

**Comment by fdortu** [comment]
Il faudrait d'abord que l'utilisateur qui s'enregistre puisse choisir le type de membre qu'il souhaite devenir: sympathisant ou effectif.

S'il choisi d'être membre effectif, il faudrait avoir un champ à choix multitples pour cocher un des trois collèges. 

S'il choisit un des collèges de type prestataire (commerçant ou association), le CA devra vérifier la pertinence de la demande avant de vraiment activier son adhésion.

Une fois l'adhésion acceptée, il aura la possibilité de rajouter un ou des commerces (plus tard, via Mon espace Ropi -> Mes commerces). 

Dis moi si c'est clair et si tu penses que c'est la bonne façon de procéder?

**Comment by Laurent5** [comment]
-> Sur le formulaire d'inscription possibilité de montrer sa volonté de se faire membre effectif

**Comment by Laurent5** [comment]
Liaison faite à l'inscription, mais il faudra permettre de le faire par la suite -> Moins prioritaire.
