### ISSUE TITLE
Impossible de choisir tous les commerces dans le système de commande de ropi

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#67]
Quand je comande des ropi, si je chosis le mode de livraison chez le commerçant, seul le commerce 'Fonds du Petit Marais' apparait dans la liste, alors qu'il y a deux autres commerces enregistrés.

Idéalement, il faudrait ajouter un flag pour chaque commerce, pour savoir s'il a choisi ou pas de distribuer des ropi commandés.

**Comment by Laurent5** [comment]
C'est déjà le cas. En fait je n'ai oser parler qu'au nom  du fonds du petit marais :p

Je rajoute par contre la fonctionnalité dans l'espace d'administration des commerces de cocher/décocher cette option.
