### ISSUE TITLE
Possibilité de rajouté lien dynamique

### ISSUE THREAD

**Issue by samouraii** [RopiMons/siteWebV2#70]

**Comment by Laurent5** [comment]
Coucou, peux-tu préciser ? Est-ce dans la même optique que #33 ?

**Comment by samouraii** [comment]
Je vois par la la possibilité de rajouté les pages de type /my/account, /admin/users/listening

**Comment by Laurent5** [comment]
Oki :-) 

Envoyé depuis mon appareil Android.

-----Original Message-----

**Comment by Laurent5** [comment]
Résolution via #33
