### ISSUE TITLE
commande de ropi: affichage des boutons "chez un commerçant" et "chez moi" trop large

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#73]
Dans le système de commande des ropi, l'affichage des boutons "chez un commerçant" et "chez moi" est trop large (dépasse de la colonne, voir image pièce jointe). Aussi, on ne voit pas clairement quel bouton a été cliqué. Il faudrait que la box soit encadrée pour voir qu'elle est sélectionnée.

Solution alternative plus simple: un simple check box (exclusif) serait suffisant, voir même mieux

Voir image jointe.
![untitled](https://cloud.githubusercontent.com/assets/7003203/12032642/ac6cc792-ae1a-11e5-9361-a1e31a91525b.png)

**Comment by fdortu** [comment]
La situation est déjà améliorée mais je les réduirais encore un peu. Aussi ajouter une bordure au bouton pour que ça ressorte bien

**Comment by Laurent5** [comment]
@samouraii @JoBierna vous savez prendre en charge ?
