### ISSUE TITLE
Orthographe

### ISSUE THREAD

**Issue by JoBierna** [RopiMons/siteWebV2#82]
Ropi >>  Ecouler ses ropis bas de la page t de taxe
![taxe](https://cloud.githubusercontent.com/assets/12040885/15684629/4b4cd3f4-2768-11e6-85b9-7e06b34407b8.jpg)

Ropi >>  Le ropi, mode d'emploi  ç 
![commercant](https://cloud.githubusercontent.com/assets/12040885/15684742/b90eb448-2768-11e6-9e85-ead48fd59f8c.jpg)
Ropi >>  Nous aider 
![indispensable](https://cloud.githubusercontent.com/assets/12040885/15685503/4d0673e0-276c-11e6-9d09-c8554c24326d.png)

**Comment by fdortu** [comment]
fait
