### ISSUE TITLE
Impossible de rééditer les news en cliquant sur le boutton edit.

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#87]
Voici l'erreur obtenue en cliquant sur le bouton edit

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by samouraii** [comment]
Oui c'est un dump si je ne me trompe pas qui est en trop

**Comment by fdortu** [comment]
Ok super, Laurent me dit qu'il peut corriger ça !
