### ISSUE TITLE
Les news n'apparaissent pas sur l'écran d'acceuil

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#88]
Voici une copie de la page d'accueil alors qu'une news a été créée

![nodisplaynews](https://cloud.githubusercontent.com/assets/7003203/15716792/55fc278e-2824-11e6-936e-8a1f3197a640.jpg)

**Comment by samouraii** [comment]
Bah logique tu as pas validé la news .... une news non active = une news non visible  mais ici j'ai un dump sur la modification de la news donc tu sais pas la modifier je regarderai cela demain

**Comment by Laurent5** [comment]
Coucou,

Si c'est un pblm de dump, je peux y regarder ... Merci :-)

**Comment by samouraii** [comment]
J'ai deja fait

**Comment by samouraii** [comment]
j'ai oublié de le fixer
