### ISSUE TITLE
Permettre de pouvoir éditer ses coordonnées perso dans l'espace membre

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#89]
Je voudrais bien changer mes coordonnées dans l'espace membre.
Par exemple mon compte "fdortu" est enregistré avec le nom "Laurent Cardon".

**Comment by samouraii** [comment]
c'est déjà possible mais faut rajouter un lien: le nom du lien est "ropi_account"

**Comment by Laurent5** [comment]
Bingo, je m'en charge ... Merci !

**Comment by samouraii** [comment]
avec plaisir
