### ISSUE TITLE
Message erreur quand je sauve mes coordonnée

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#93]
Quand j'enregistre mes coordonnées d'utilisateur (http://dev.ropi.be/my/account/modification/), j'obtiens le message suivant : "Cette adresse email est déjà enregistrée dans notre système"

![bugusercoordmail](https://cloud.githubusercontent.com/assets/7003203/15719416/1fec6e40-2830-11e6-814d-bd618fe41d80.png)

Le même genre de problème se produit quand j'édite via l'interface admin

**Comment by Laurent5** [comment]
Je n'arrive pas à reproduire le bug ...

**Comment by Laurent5** [comment]
Problème résolus via purge sur le serveur de prod de la BDD. Testé par @fdortu
