### ISSUE TITLE
Déplacer le Fork me on github en bas à droite ET supprimer bandeau site en construction

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#98]
Le Fork me on github est trop gênant sur le smartphone -> à déplacer en bas à droite (ou à gauche, pas de religion en la matière)

Enlever le bandeau site en construction.

Comme ça je peux faire des capture d'écran pour le vademecum des commerçants

**Comment by Laurent5** [comment]
@samouraii tu sais prendre le relais pour la banière "Fork me" ?
