### ISSUE TITLE
création d'un commerce par un utlisateur - modification des droits

### ISSUE THREAD

**Issue by fdortu** [RopiMons/siteWebV2#99]
Lors de la création d'un commerce par un utilisateur, laisser le commerce apparent (ce qui permet à l'utilisateur de faire des corrections ultérieures), càd que l'utilisateur est automatiquement upgradé au status de commerçant.

Cependant son commerce n'est pas visible publiquement tant que pas validé par un admin.

**Comment by Laurent5** [comment]
Au niveau de l'attribution du statut de commarçant :+1: 
-> A chaque login de la personne ce droit est remis en question, si la personne possède au moins un commerce (Validé ou non) alors il acquiet le droit commerçant.
